CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 identifier VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
 name VARCHAR(150) NOT NULL,
 role ENUM('Administrator','Gestor') NOT NULL,
 active BOOLEAN NOT NULL DEFAULT TRUE,
 password_hash VARCHAR(255) NULL,
 webauthn_handle BINARY(32) NOT NULL UNIQUE,
 session_version INT UNSIGNED NOT NULL DEFAULT 1,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS app_locks (id INT PRIMARY KEY) ENGINE=InnoDB;
INSERT IGNORE INTO app_locks (id) VALUES (1);
CREATE TABLE IF NOT EXISTS pattern_credentials (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL UNIQUE,
 pattern_hash VARCHAR(255) NOT NULL,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS biometric_templates (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 modality ENUM('face','voice') NOT NULL,
 ciphertext MEDIUMBLOB NOT NULL,
 nonce BINARY(24) NOT NULL,
 key_version VARCHAR(20) NOT NULL,
 model_version VARCHAR(150) NOT NULL,
 threshold_version VARCHAR(150) NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY user_modality(user_id,modality),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS webauthn_credentials (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 credential_id VARBINARY(1024) NOT NULL,
 credential_digest BINARY(32) NOT NULL UNIQUE,
 public_key TEXT NOT NULL,
 sign_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
 transports JSON NOT NULL,
 backup_eligible BOOLEAN NOT NULL,
 backup_state BOOLEAN NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS auth_challenges (
 id CHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
 user_id BIGINT UNSIGNED NULL,
 identifier_digest CHAR(64) NOT NULL,
 session_binding CHAR(64) NOT NULL,
 purpose ENUM('auth','enroll') NOT NULL,
 method ENUM('face','voice','webauthn','pattern') NOT NULL,
 challenge VARBINARY(64) NOT NULL,
 session_version INT UNSIGNED NULL,
 expires_at DATETIME NOT NULL,
 consumed_at DATETIME NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX(expires_at),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS access_attempts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NULL,
 identifier_digest CHAR(64) NOT NULL,
 ip_digest CHAR(64) NOT NULL,
 method VARCHAR(20) NOT NULL,
 outcome ENUM('request','success','failure','error','limited') NOT NULL,
 reason_code VARCHAR(60) NOT NULL,
 request_id CHAR(32) NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX account_rate(identifier_digest,created_at),
 INDEX origin_rate(ip_digest,created_at),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS audit_events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 actor_id BIGINT UNSIGNED NULL,
 target_user_id BIGINT UNSIGNED NULL,
 action VARCHAR(80) NOT NULL,
 request_id CHAR(32) NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(actor_id) REFERENCES users(id) ON DELETE SET NULL,
 FOREIGN KEY(target_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS consents (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 modality ENUM('face','voice') NOT NULL,
 notice_version VARCHAR(30) NOT NULL,
 granted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 withdrawn_at DATETIME NULL,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
